language: php

sudo: false

cache:
  directories:
    - "$HOME/.composer/cache"

env:
  - COMPOSER_FLAGS="--prefer-stable"

matrix:
  include:
    - php: 7.1
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="3.3.*"
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.0.*"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="3.3.*"
    - php: 7.2
      env: COMPOSER_FLAGS="" SYMFONY_VERSION="4.0.*"

before_install: if [[ "$SYMFONY_VERSION" != "" ]]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: composer update $COMPOSER_FLAGS --prefer-dist

script: vendor/bin/phpunit
